package com.aznos.world

/**
 * A collection of all the blocks in the game
 */
enum class Blocks(val id: Int, val string: String) {
    AIR(0, "air"),
    STONE(1, "stone"),
    GRANITE(2, "granite"),
    POLISHED_GRANITE(3, "polished_granite"),
    DIORITE(4, "diorite"),
    POLISHED_DIORITE(5, "polished_diorite"),
    ANDESITE(6, "andesite"),
    POLISHED_ANDESITE(7, "polished_andesite"),
    SNOWY_GRASS_BLOCK(8, "snowy_grass_block"),
    GRASS_BLOCK(9, "grass_block"),
    DIRT(10, "dirt"),
    COARSE_DIRT(11, "coarse_dirt"),
    GRASS_PATH(12, "grass_path"),
    PODZOL(13, "podzol"),
    COBBLESTONE(14, "cobblestone"),
    OAK_PLANKS(15, "oak_planks"),
    SPRUCE_PLANKS(16, "spruce_planks"),
    BIRCH_PLANKS(17, "birch_planks"),
    JUNGLE_PLANKS(18, "jungle_planks"),
    ACACIA_PLANKS(19, "acacia_planks"),
    DARK_OAK_PLANKS(20, "dark_oak_planks"),
    OAK_SAPLING(21, "oak_sapling"),
    OAK_SAPLING_VARIANT(22, "oak_sapling_variant"),
    SPRUCE_SAPLING(23, "spruce_sapling"),
    SPRUCE_SAPLING_VARIANT(24, "spruce_sapling_variant"),
    BIRCH_SAPLING(25, "birch_sapling"),
    BIRCH_SAPLING_VARIANT(26, "birch_sapling_variant"),
    JUNGLE_SAPLING(27, "jungle_sapling"),
    JUNGLE_SAPLING_VARIANT(28, "jungle_sapling_variant"),
    ACACIA_SAPLING(29, "acacia_sapling"),
    ACACIA_SAPLING_VARIANT(30, "acacia_sapling_variant"),
    DARK_OAK_SAPLING(31, "dark_oak_sapling"),
    DARK_OAK_SAPLING_VARIANT(32, "dark_oak_sapling_variant"),
    BEDROCK(33, "bedrock"),
    WATER_1(34, "water_1"),
    WATER_2(35, "water_2"),
    WATER_3(36, "water_3"),
    WATER_4(37, "water_4"),
    WATER_5(38, "water_5"),
    WATER_6(39, "water_6"),
    WATER_7(40, "water_7"),
    WATER_8(41, "water_8"),
    WATER_9(42, "water_9"),
    WATER_10(43, "water_10"),
    WATER_11(44, "water_11"),
    WATER_12(45, "water_12"),
    WATER_13(46, "water_13"),
    WATER_14(47, "water_14"),
    WATER_15(48, "water_15"),
    WATER_16(49, "water_16"),
    WATER_17(50, "water_17"),
    WATER_18(51, "water_18"),
    WATER_19(52, "water_19"),
    WATER_20(53, "water_20"),
    WATER_21(54, "water_21"),
    WATER_22(55, "water_22"),
    WATER_23(56, "water_23"),
    WATER_24(57, "water_24"),
    WATER_25(58, "water_25"),
    WATER_26(59, "water_26"),
    WATER_27(60, "water_27"),
    WATER_28(61, "water_28"),
    WATER_29(62, "water_29"),
    WATER_30(63, "water_30"),
    WATER_31(64, "water_31"),
    WATER_32(65, "water_32"),
    SAND(66, "sand"),
    RED_SAND(67, "red_sand"),
    GRAVEL(68, "gravel"),
    GOLD_ORE(69, "gold_ore"),
    IRON_ORE(70, "iron_ore"),
    COAL_ORE(71, "coal_ore"),
    NETHER_GOLD_ORE(72, "nether_gold_ore"),
    OAK_LOG_FACING_HORIZONTAL(73, "oak_log_facing_horizontal"),
    OAK_LOG_FACING_UP(74, "oak_log_facing_up"),
    OAK_LOG_FACING_VERTICAL(75, "oak_log_facing_vertical"),
    SPRUCE_LOG_FACING_HORIZONTAL(76, "spruce_log_facing_horizontal"),
    SPRUCE_LOG_FACING_UP(77, "spruce_log_facing_up"),
    SPRUCE_LOG_FACING_VERTICAL(78, "spruce_log_facing_vertical"),
    BIRCH_LOG_FACING_HORIZONTAL(79, "birch_log_facing_horizontal"),
    BIRCH_LOG_FACING_UP(80, "birch_log_facing_up"),
    BIRCH_LOG_FACING_VERTICAL(81, "birch_log_facing_vertical"),
    JUNGLE_LOG_FACING_HORIZONTAL(82, "jungle_log_facing_horizontal"),
    JUNGLE_LOG_FACING_UP(83, "jungle_log_facing_up"),
    JUNGLE_LOG_FACING_VERTICAL(84, "jungle_log_facing_vertical"),
    ACACIA_LOG_FACING_HORIZONTAL(85, "acacia_log_facing_horizontal"),
    ACACIA_LOG_FACING_UP(86, "acacia_log_facing_up"),
    ACACIA_LOG_FACING_VERTICAL(87, "acacia_log_facing_vertical"),
    DARK_OAK_LOG_FACING_HORIZONTAL(88, "dark_oak_log_facing_horizontal"),
    DARK_OAK_LOG_FACING_UP(89, "dark_oak_log_facing_up"),
    DARK_OAK_LOG_FACING_VERTICAL(90, "dark_oak_log_facing_vertical"),
    STRIPPED_SPRUCE_LOG_FACING_HORIZONTAL(91, "stripped_spruce_log_facing_horizontal"),
    STRIPPED_SPRUCE_LOG_FACING_UP(92, "stripped_spruce_log_facing_up"),
    STRIPPED_SPRUCE_LOG_FACING_VERTICAL(93, "stripped_spruce_log_facing_vertical"),
    STRIPPED_BIRCH_LOG_FACING_HORIZONTAL(94, "stripped_birch_log_facing_horizontal"),
    STRIPPED_BIRCH_LOG_FACING_UP(95, "stripped_birch_log_facing_up"),
    STRIPPED_BIRCH_LOG_FACING_VERTICAL(96, "stripped_birch_log_facing_vertical"),
    STRIPPED_JUNGLE_LOG_FACING_HORIZONTAL(97, "stripped_jungle_log_facing_horizontal"),
    STRIPPED_JUNGLE_LOG_FACING_UP(98, "stripped_jungle_log_facing_up"),
    STRIPPED_JUNGLE_LOG_FACING_VERTICAL(99, "stripped_jungle_log_facing_vertical"),
    STRIPPED_ACACIA_LOG_FACING_HORIZONTAL(100, "stripped_acacia_log_facing_horizontal"),
    STRIPPED_ACACIA_LOG_FACING_UP(101, "stripped_acacia_log_facing_up"),
    STRIPPED_ACACIA_LOG_FACING_VERTICAL(102, "stripped_acacia_log_facing_vertical"),
    STRIPPED_DARK_OAK_LOG_FACING_HORIZONTAL(103, "stripped_dark_oak_log_facing_horizontal"),
    STRIPPED_DARK_OAK_LOG_FACING_UP(104, "stripped_dark_oak_log_facing_up"),
    STRIPPED_DARK_OAK_LOG_FACING_VERTICAL(105, "stripped_dark_oak_log_facing_vertical"),
    STRIPPED_OAK_LOG_FACING_HORIZONTAL(106, "stripped_oak_log_facing_horizontal"),
    STRIPPED_OAK_LOG_FACING_UP(107, "stripped_oak_log_facing_up"),
    STRIPPED_OAK_LOG_FACING_VERTICAL(108, "stripped_oak_log_facing_vertical"),
    OAK_WOOD_FACING_HORIZONTAL(109, "oak_wood_facing_horizontal"),
    OAK_WOOD_FACING_UP(110, "oak_wood_facing_up"),
    OAK_WOOD_FACING_VERTICAL(111, "oak_wood_facing_vertical"),
    SPRUCE_WOOD_FACING_HORIZONTAL(112, "spruce_wood_facing_horizontal"),
    SPRUCE_WOOD_FACING_UP(113, "spruce_wood_facing_up"),
    SPRUCE_WOOD_FACING_VERTICAL(114, "spruce_wood_facing_vertical"),
    BIRCH_WOOD_FACING_HORIZONTAL(115, "birch_wood_facing_horizontal"),
    BIRCH_WOOD_FACING_UP(116, "birch_wood_facing_up"),
    BIRCH_WOOD_FACING_VERTICAL(117, "birch_wood_facing_vertical"),
    JUNGLE_WOOD_FACING_HORIZONTAL(118, "jungle_wood_facing_horizontal"),
    JUNGLE_WOOD_FACING_UP(119, "jungle_wood_facing_up"),
    JUNGLE_WOOD_FACING_VERTICAL(120, "jungle_wood_facing_vertical"),
    ACACIA_WOOD_FACING_HORIZONTAL(121, "acacia_wood_facing_horizontal"),
    ACACIA_WOOD_FACING_UP(122, "acacia_wood_facing_up"),
    ACACIA_WOOD_FACING_VERTICAL(123, "acacia_wood_facing_vertical"),
    DARK_OAK_WOOD_FACING_HORIZONTAL(124, "dark_oak_wood_facing_horizontal"),
    DARK_OAK_WOOD_FACING_UP(125, "dark_oak_wood_facing_up"),
    DARK_OAK_WOOD_FACING_VERTICAL(126, "dark_oak_wood_facing_vertical"),
    STRIPPED_OAK_WOOD_FACING_HORIZONTAL(127, "stripped_oak_wood_facing_horizontal"),
    STRIPPED_OAK_WOOD_FACING_UP(128, "stripped_oak_wood_facing_up"),
    STRIPPED_OAK_WOOD_FACING_VERTICAL(129, "stripped_oak_wood_facing_vertical"),
    STRIPPED_SPRUCE_WOOD_FACING_HORIZONTAL(130, "stripped_spruce_wood_facing_horizontal"),
    STRIPPED_SPRUCE_WOOD_FACING_UP(131, "stripped_spruce_wood_facing_up"),
    STRIPPED_SPRUCE_WOOD_FACING_VERTICAL(132, "stripped_spruce_wood_facing_vertical"),
    STRIPPED_BIRCH_WOOD_FACING_HORIZONTAL(133, "stripped_birch_wood_facing_horizontal"),
    STRIPPED_BIRCH_WOOD_FACING_UP(134, "stripped_birch_wood_facing_up"),
    STRIPPED_BIRCH_WOOD_FACING_VERTICAL(135, "stripped_birch_wood_facing_vertical"),
    STRIPPED_JUNGLE_WOOD_FACING_HORIZONTAL(136, "stripped_jungle_wood_facing_horizontal"),
    STRIPPED_JUNGLE_WOOD_FACING_UP(137, "stripped_jungle_wood_facing_up"),
    STRIPPED_JUNGLE_WOOD_FACING_VERTICAL(138, "stripped_jungle_wood_facing_vertical"),
    STRIPPED_ACACIA_WOOD_FACING_HORIZONTAL(139, "stripped_acacia_wood_facing_horizontal"),
    STRIPPED_ACACIA_WOOD_FACING_UP(140, "stripped_acacia_wood_facing_up"),
    STRIPPED_ACACIA_WOOD_FACING_VERTICAL(141, "stripped_acacia_wood_facing_vertical"),
    STRIPPED_DARK_OAK_WOOD_FACING_HORIZONTAL(142, "stripped_dark_oak_wood_facing_horizontal"),
    STRIPPED_DARK_OAK_WOOD_FACING_VERTICAL(143, "stripped_dark_oak_wood_facing_vertical"),
    OAK_LEAVES_1(144, "oak_leaves_1"),
    OAK_LEAVES_2(145, "oak_leaves_2"),
    OAK_LEAVES_3(146, "oak_leaves_3"),
    OAK_LEAVES_4(147, "oak_leaves_4"),
    OAK_LEAVES_5(148, "oak_leaves_5"),
    OAK_LEAVES_6(149, "oak_leaves_6"),
    OAK_LEAVES_7(150, "oak_leaves_7"),
    OAK_LEAVES_8(151, "oak_leaves_8"),
    OAK_LEAVES_9(152, "oak_leaves_9"),
    OAK_LEAVES_10(153, "oak_leaves_10"),
    OAK_LEAVES_11(154, "oak_leaves_11"),
    OAK_LEAVES_12(155, "oak_leaves_12"),
    OAK_LEAVES_13(156, "oak_leaves_13"),
    OAK_LEAVES_14(157, "oak_leaves_14"),
    SPRUCE_LEAVES_1(158, "spruce_leaves_1"),
    SPRUCE_LEAVES_2(159, "spruce_leaves_2"),
    SPRUCE_LEAVES_3(160, "spruce_leaves_3"),
    SPRUCE_LEAVES_4(161, "spruce_leaves_4"),
    SPRUCE_LEAVES_5(162, "spruce_leaves_5"),
    SPRUCE_LEAVES_6(163, "spruce_leaves_6"),
    SPRUCE_LEAVES_7(164, "spruce_leaves_7"),
    SPRUCE_LEAVES_8(165, "spruce_leaves_8"),
    SPRUCE_LEAVES_9(166, "spruce_leaves_9"),
    SPRUCE_LEAVES_10(167, "spruce_leaves_10"),
    SPRUCE_LEAVES_11(168, "spruce_leaves_11"),
    SPRUCE_LEAVES_12(169, "spruce_leaves_12"),
    SPRUCE_LEAVES_13(170, "spruce_leaves_13"),
    SPRUCE_LEAVES_14(171, "spruce_leaves_14"),
    BIRCH_LEAVES_1(172, "birch_leaves_1"),
    BIRCH_LEAVES_2(173, "birch_leaves_2"),
    BIRCH_LEAVES_3(174, "birch_leaves_3"),
    BIRCH_LEAVES_4(175, "birch_leaves_4"),
    BIRCH_LEAVES_5(176, "birch_leaves_5"),
    BIRCH_LEAVES_6(177, "birch_leaves_6"),
    BIRCH_LEAVES_7(178, "birch_leaves_7"),
    BIRCH_LEAVES_8(179, "birch_leaves_8"),
    BIRCH_LEAVES_9(180, "birch_leaves_9"),
    BIRCH_LEAVES_10(181, "birch_leaves_10"),
    BIRCH_LEAVES_11(182, "birch_leaves_11"),
    BIRCH_LEAVES_12(183, "birch_leaves_12"),
    BIRCH_LEAVES_13(184, "birch_leaves_13"),
    BIRCH_LEAVES_14(185, "birch_leaves_14"),
    JUNGLE_LEAVES_1(186, "jungle_leaves_1"),
    JUNGLE_LEAVES_2(187, "jungle_leaves_2"),
    JUNGLE_LEAVES_3(188, "jungle_leaves_3"),
    JUNGLE_LEAVES_4(189, "jungle_leaves_4"),
    JUNGLE_LEAVES_5(190, "jungle_leaves_5"),
    JUNGLE_LEAVES_6(191, "jungle_leaves_6"),
    JUNGLE_LEAVES_7(192, "jungle_leaves_7"),
    JUNGLE_LEAVES_8(193, "jungle_leaves_8"),
    JUNGLE_LEAVES_9(194, "jungle_leaves_9"),
    JUNGLE_LEAVES_10(195, "jungle_leaves_10"),
    JUNGLE_LEAVES_11(196, "jungle_leaves_11"),
    JUNGLE_LEAVES_12(197, "jungle_leaves_12"),
    JUNGLE_LEAVES_13(198, "jungle_leaves_13"),
    JUNGLE_LEAVES_14(199, "jungle_leaves_14"),
    ACACIA_LEAVES_1(200, "acacia_leaves_1"),
    ACACIA_LEAVES_2(201, "acacia_leaves_2"),
    ACACIA_LEAVES_3(202, "acacia_leaves_3"),
    ACACIA_LEAVES_4(203, "acacia_leaves_4"),
    ACACIA_LEAVES_5(204, "acacia_leaves_5"),
    ACACIA_LEAVES_6(205, "acacia_leaves_6"),
    ACACIA_LEAVES_7(206, "acacia_leaves_7"),
    ACACIA_LEAVES_8(207, "acacia_leaves_8"),
    ACACIA_LEAVES_9(208, "acacia_leaves_9"),
    ACACIA_LEAVES_10(209, "acacia_leaves_10"),
    ACACIA_LEAVES_11(210, "acacia_leaves_11"),
    ACACIA_LEAVES_12(211, "acacia_leaves_12"),
    ACACIA_LEAVES_13(212, "acacia_leaves_13"),
    ACACIA_LEAVES_14(213, "acacia_leaves_14"),
    DARK_OAK_LEAVES_1(214, "dark_oak_leaves_1"),
    DARK_OAK_LEAVES_2(215, "dark_oak_leaves_2"),
    DARK_OAK_LEAVES_3(216, "dark_oak_leaves_3"),
    DARK_OAK_LEAVES_4(217, "dark_oak_leaves_4"),
    DARK_OAK_LEAVES_5(218, "dark_oak_leaves_5"),
    DARK_OAK_LEAVES_6(219, "dark_oak_leaves_6"),
    DARK_OAK_LEAVES_7(220, "dark_oak_leaves_7"),
    DARK_OAK_LEAVES_8(221, "dark_oak_leaves_8"),
    DARK_OAK_LEAVES_9(222, "dark_oak_leaves_9"),
    DARK_OAK_LEAVES_10(223, "dark_oak_leaves_10"),
    DARK_OAK_LEAVES_11(224, "dark_oak_leaves_11"),
    DARK_OAK_LEAVES_12(225, "dark_oak_leaves_12"),
    DARK_OAK_LEAVES_13(226, "dark_oak_leaves_13"),
    DARK_OAK_LEAVES_14(227, "dark_oak_leaves_14"),
    SPONGE(228, "sponge"),
    WET_SPONGE(229, "wet_sponge"),
    GLASS(230, "glass"),
    LAPIS_ORE(231, "lapis_ore"),
    LAPIS_BLOCK(232, "lapis_block"),
    DISPENSER_FACING_NORTH_TRIGGERED(233, "dispenser_facing_north_1"),
    DISPENSER_FACING_NORTH(234, "dispenser_facing_north_2"),
    DISPENSER_FACING_EAST_TRIGGERED(235, "dispenser_facing_east_1"),
    DISPENSER_FACING_EAST_2(236, "dispenser_facing_east_2"),
    DISPENSER_FACING_SOUTH_TRIGGERED(237, "dispenser_facing_south_1"),
    DISPENSER_FACING_SOUTH_2(238, "dispenser_facing_south_2"),
    DISPENSER_FACING_WEST_TRIGGERED(239, "dispenser_facing_west_1"),
    DISPENSER_FACING_WEST_2(240, "dispenser_facing_west_2"),
    DISPENSER_FACING_UP_TRIGGERED(241, "dispenser_facing_up_1"),
    DISPENSER_FACING_UP_2(242, "dispenser_facing_up_2"),
    DISPENSER_FACING_DOWN_TRIGGERED(243, "dispenser_facing_down_1"),
    DISPENSER_FACING_DOWN_2(244, "dispenser_facing_down_2"),
    SANDSTONE(245, "sandstone"),
    CHISELED_SANDSTONE(246, "chiseled_sandstone"),
    NOTEBLOCK_POWERED_0(247, "noteblock_powered_0"),
    NOTEBLOCK_0(248, "noteblock_0"),
    NOTEBLOCK_POWERED_1(249, "noteblock_powered_1"),
    NOTEBLOCK_1(250, "noteblock_1");


    @Suppress("unused")
    companion object {
        /**
         * Returns a block from its ID
         *
         * @param id The ID of the block
         * @return The block with the given ID
         */
        fun getBlockFromID(id: Int): Blocks {
            for(block in entries) {
                if(block.id == id) {
                    return block
                }
            }

            return AIR
        }

        /**
         * Returns a block from its string
         *
         * @param string The string of the block
         * @return The block with the given string
         */
        fun getBlockFromString(string: String): Blocks {
            for(block in entries) {
                if(block.string == string) {
                    return block
                }
            }

            return AIR
        }
    }
}